### ISSUE TITLE
Song information from Spicetify & (spotify web player) not being detected by Webnowplaying 

### ISSUE THREAD

**Issue by RandomName50** [keifufu/WebNowPlaying-Rainmeter#24]

**Comment by keifufu** [comment]
are you ok

**Comment by RandomName50** [comment]
*Sorry I accidentally opened an issue and submitted it too early with nothing written down.

I installed the rainmeter skin (v2.07) and it isn't picking up any information from spicetify which I had already configured to use webnowplaying.js.

**Comment by keifufu** [comment]
Spicetify is no longer needed, the plugin will pick up the spotify desktop app as long as you have "show desktop overlay when using media keys" enabled. The web version will work once you install the webnowplaying browser extension (well, it should.. the extension might still be outdated since spotify updated things again).

**Comment by RandomName50** [comment]
Well, unfortunately, despite having "show desktop overlay when using media keys" enabled, Spotify will still not show up on the rainmeter skins that use the WNP plugin and the WNP browser extension doesn't also detect the Spotify web player.
